---
- name: reload systemd
  become: true
  systemd:
    name: nginx
    daemon_reload: "True"

- name: reload nginx
  become: true
  service:
    name: "{{ nginx_system_service }}"
    state: reloaded
