---
- name: reload systemd
  become: true
  systemd:
    name: nats-server
    daemon_reload: "True"

- name: restart nats
  become: true
  service:
    name: nats-server
    state: restarted

- name: reload nats
  become: true
  service:
    name: nats-server
    state: reloaded

- name: start nats
  become: true
  service:
    name: nats-server
    enabled: "True"
    state: started
