---
- name: reload clickhouse-server
  become: false
  debug:
    msg: Clickhouse configuration was changed. hope it will reload it automaticaly

- name: restart clickhouse-server
  become: true
  service:
    name: "{{ clickhouse_service_name }}"
    state: restarted
