name: Bug report
description: Report a bug. For security vulnerabilities see Report a security vulnerability in the templates.
title: "BUG: <Please write a comprehensive title after the 'BUG: ' prefix>"
labels: [bug]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. Before creating a new
        issue, please make sure to take a few minutes to check the issue tracker
        for existing issues about the bug.

  - type: textarea
    attributes:
      label: "Describe the issue:"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Reproduce the example:"
      description: >
        A short example that reproduces the problem/missing feature.
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Error message:"
      description: >
        Please include full error message, if any.
      placeholder: |
        << Full traceback starting from `Traceback: ...` >>
      render: shell

  - type: textarea
    attributes:
      label: "System information"
      description: Output from `./noc tech-report`
    validations:
      required: true
