---
- name: reload systemd
  become: true
  systemd:
    name: grafana-server
    daemon_reload: "True"

- name: restart grafana
  become: true
  service:
    name: "{{ grafana_system_service }}"
    state: restarted
