# ---------------------------------------------------------------------
# BIND-compatible zonefile generator
# ---------------------------------------------------------------------
# Copyright (C) 2007-2019 The NOC Project
# See LICENSE for details
# ---------------------------------------------------------------------

# NOC modules
from .encoding import from_idna, to_idna, is_idna
from .rr import RR

HEADER = """;;
;; %s
;; WARNING: Auto-generated zone file
;; Do not edit manually
;; Generated by NOC (http://getnoc.com)
;;"""

FOOTER = """;;
;; End of auto-generated zone
;;
"""


class ZoneFile:
    TABSTOP = 8
    MAX_TXT = 128

    def __init__(self, data) -> None:
        records = data.get("records", [])
        if not records:
            raise ValueError("Zone must contain SOA record")
        self.zone = data["name"]
        if RR(zone=self.zone, **records[0]).type != "SOA":
            raise ValueError("First record must be SOA")
        self.records = [RR(zone=self.zone, **r) for r in records]

    def get_text(self):
        primary, contact, serial, refresh, retry, expire, ttl = self.records[0].rdata.split()
        serial = int(serial)
        refresh = int(refresh)
        retry = int(retry)
        expire = int(expire)
        ttl = int(ttl)
        if "@" in contact:
            contact = contact.replace("@", ".")
        if not contact.endswith("."):
            contact += "."

        suffix = to_idna(self.zone + ".")
        nsuffix = "." + suffix
        lnsuffix = len(nsuffix)

        # SOA
        z = [
            HEADER % from_idna(self.zone),
            f"""$ORIGIN {self.zone}.
$TTL {int(ttl)}
@ IN SOA {primary} {contact} (
    {int(serial)} ; serial
    {int(refresh)}       ; refresh ({self.pretty_time(refresh)})
    {int(retry)}        ; retry ({self.pretty_time(retry)})
    {int(expire)}      ; expire ({self.pretty_time(expire)})
    {int(ttl)}       ; minimum ({self.pretty_time(ttl)})
    )""",
        ]
        # Add records
        rr = []
        for r in self.records[1:]:
            name = r.name
            content = r.rdata
            if r.type == "CNAME" and r.rdata.endswith(nsuffix):
                # Strip domain from content
                content = content[:-lnsuffix]
            if r.priority:
                content = f"{r.priority} {content}"
            rr += [(name, r.type, content)]
        # prepare mask for 3-column format
        if rr:
            l1 = max(len(r[0]) for r in rr)
            l2 = max(len(r[1]) for r in rr)
            # Ceil to boundary of 4
            l1 = (l1 // self.TABSTOP + 1) * self.TABSTOP
            l2 = (l2 // self.TABSTOP + 1) * self.TABSTOP
        else:
            l1 = self.TABSTOP
            l2 = self.TABSTOP
        # Add RRs
        for r in rr:
            if is_idna(r[0]):
                z += [f"; {from_idna(r[0])}"]
            if r[1] == "TXT":
                content = self.split_txt(r[2])
                z += [f"{r[0]:<{l1}}{r[1]:<{l2}}{content.pop(0)}"]
                for c in content:
                    z += [f"{' ' * l1}{c}"]
            else:
                z += [f"{r[0]:<{l1}}{r[1]:<{l2}}{r[2]}"]
        z += [FOOTER]
        return "\n".join(z)

    @staticmethod
    def pretty_time(t):
        """
        Format seconds to human-readable time for comments
        :return:
        """
        if not t:
            return "zero"
        T = ["week", "day", "hour", "min", "sec"]
        W = [604800, 86400, 3600, 60, 1]
        r = []
        for w in W:
            rr = t // w
            t -= rr * w
            r += [rr]
        z = []
        for rr, t in zip(r, T):
            if rr > 1:
                z += [f"{int(rr)} {t}s"]
            elif rr > 0:
                z += [f"{int(rr)} {t}"]
        return " ".join(z)

    @classmethod
    def split_txt(cls, value):
        """
        Split TXT to up-to MAX_TXT parts
        :return:
        """
        if len(value) <= cls.MAX_TXT:
            if value[0] != '"':
                value = f'"{value}"'
            return [value]
        if value[0] == '"' and value[-1] == '"':
            value = value[1:-1]
        v = ["("]
        while value:
            v += [f'"{value[: cls.MAX_TXT]}"']
            value = value[cls.MAX_TXT :]
        v += [")"]
        return v
