---
- name: reload systemd
  become: true
  systemd:
    name: "{{ postgres_system_service }}"
    daemon_reload: "True"

- name: reload postgres
  become: true
  service:
    name: "{{ postgres_system_service }}"
    state: reloaded

- name: restart postgres
  become: true
  service:
    name: "{{ postgres_system_service }}"
    state: restarted
