---
- name: reload systemd
  become: true
  systemd:
    name: liftbridge
    daemon_reload: "True"

- name: restart liftbridge
  become: true
  service:
    name: liftbridge
    state: restarted

- name: reload liftbridge
  become: true
  service:
    name: liftbridge
    state: reloaded

- name: start liftbridge
  become: true
  service:
    name: liftbridge
    enabled: "True"
    state: started
