# Debian 11 is EOL platform
- name: Install Debian system packages
  apt:
    name: "{{ packages }}"
    state: present # install once, there will not be any updates
    update_cache: "False"
  vars:
    # Ignore repo expire
    ansible_apt_update_cache_extra_args: "-o Acquire::Check-Valid-Until=false"
    packages:
      - ca-certificates
      - unzip
      - sudo
      - curl
      - apt-transport-https
      - dbus # to setup hostname
  become: true
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tags:
    - requirements
