---
- name: reload systemd
  become: true
  systemd:
    name: consul
    daemon_reload: "True"

- name: restart consul
  become: true
  service:
    name: consul
    state: restarted

- name: reload consul
  become: true
  service:
    name: consul
    state: reloaded

- name: start consul
  become: true
  service:
    name: consul
    enabled: "True"
    state: started
