name: Run Python Tests
env:
  PIP_CACHE_DIR: .pip
  PYTHONPATH: src
  TEST_PYTHON_VERSION: "3.12"
on:
  pull_request:
    paths:
      - ".github/workflows/py-tests.yml"
      - "pyproject.toml"
      - "**.py"
  release:
    types: ["published"]
jobs:
  py-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python ${{ env.TEST_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.TEST_PYTHON_VERSION }}

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ./.pip
          key: ubuntu-24.04-py-lint-${{ env.TEST_PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -IU -e .[lint]

      - name: Check Formatting
        run: ruff format --check --diff .

      - name: Check ruff
        run: ruff check -q .

  py-test:
    runs-on: ubuntu-24.04
    needs: [py-lint]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python ${{ env.TEST_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.TEST_PYTHON_VERSION }}"

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ./.pip
          key: ubuntu-24.04-py-test-${{ env.TEST_PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Run Tests
        run: pytest -v --cov --cov-branch --cov-report=xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
