name: Nightly UI Build
on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch: # allows manual trigger
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "npm"

      - name: Build UI
        run: |
          set -eux
          ./scripts/build/build-ui
          mkdir -p dist/
          tar czf dist/noc-ui-master.tar.gz -C ui/dist .

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view master > /den/null 2>&1 || \
            gh release create master --title "Master Build" --notes "Automated master builds"
          gh release upload master dist/noc-ui-master.tar.gz --clobber
